# Generated by Django 5.0.6 on 2024-05-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country_code',
        ),
    ]
