# Generated by Django 5.0.6 on 2024-05-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
    ]
