# Generated by Django 5.0.6 on 2024-05-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_id_alter_customer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='delivery_instructions',
        ),
    ]
