# Generated by Django 5.0.6 on 2024-05-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_address_delivery_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_staff',
        ),
    ]
